package educa.ead.enumerator.disciplina;

public enum DisciplinaEnum {
	TECNOLOGIA, FINANCAS, ASSUNTOS_GERAIS, CULINARIA, CIENCIAS, TEOLOGIA, ARTES, POWER_BI, ARQUEOLOGIA, GEOGRAFIA,
	HISTORIA, MATEMATICA, FISICA_QUANTICA ;

}
